- name: Remove old Docker versions
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required dependencies
  apt:
  apt:
    name: "{{ item }}"
    state: present
  loop:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key and convert to dearmored format
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Set permissions on Docker GPG key
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'

- name: Add Docker APT repository (force jammy for Ubuntu 24.04)
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable"
    filename: docker
    state: present

- name: Update apt cache after adding Docker repo
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
